service: wallet1Service

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: us-east-1
  # environment:
    # set environment variable to be accessed inside walletHandler.js file

# variables
custom:
  defaultStage: dev
  profiles:
    dev: qwsEngineerDev
    prod: qwsEngineerProd

functions:
  app:
    handler: walletHandler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  
  
  getWalletInfo:
    handler: walletHandler.handler
    events:
      - http: 'GET /getWalletInfo'
  
  
  